import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { localities } from '@/lib/data';
import { aliasesForPlace, childrenForPlace, getKnowledgePlace, knowledgeAttribution, knowledgePlaces, sourceById } from '@/lib/knowledge';
import styles from '../../knowledge.module.css';

type Props = { params: Promise<{ slug: string }> };
export function generateStaticParams(){ return knowledgePlaces.map((item) => ({ slug: item.slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata>{ const { slug } = await params; const place = getKnowledgePlace(slug); if(!place) return {}; return { title: `${place.name} — موسوعة نقادة`, description: `بيانات ${place.name} المكانية والتاريخية كما وردت في مصادر موسوعة دليل نقادة.`, alternates: { canonical: `/knowledge/places/${place.slug}` } }; }

export default async function KnowledgePlacePage({ params }: Props){ const { slug } = await params; const place = getKnowledgePlace(slug); if(!place) notFound(); const aliases = aliasesForPlace(place.name); const children = childrenForPlace(place.name); const source = sourceById(place.sourceId); const live = localities.find((item) => item.name === place.name || item.name === place.shortName); return <main id="main-content" className="page-main"><div className={`shell ${styles.wrap} ${styles.detail}`}><Link className={styles.back} href="/knowledge/places">← خريطة المكان</Link><article className={styles.detailCard}><span className={styles.eyebrow}>سجل مكاني · {place.verification === 'source_confirmed' ? 'مؤكد من المصدر' : place.verification}</span><h1>{place.name}</h1><p>{place.parent ? `موضع وارد ضمن نطاق ${place.parent}.` : 'موضع وارد ضمن مركز نقادة.'} الأرقام التاريخية المعروضة هنا تُنسب لفترتها ولا تمثل تقديرًا للسكان الحاليين.</p><div className={styles.facts}><div className={styles.fact}><small>النوع</small><b>{place.type}</b></div><div className={styles.fact}><small>التبعية</small><b>{place.parent || 'مركز نقادة'}</b></div>{place.population2014 ? <div className={styles.fact}><small>تعداد مذكور 2014</small><b>{place.population2014.toLocaleString('ar-EG')}</b></div> : null}{place.population1897 ? <div className={styles.fact}><small>تعداد 1897</small><b>{place.population1897.toLocaleString('ar-EG')}</b></div> : null}{place.houses1897 ? <div className={styles.fact}><small>مساكن 1897</small><b>{place.houses1897.toLocaleString('ar-EG')}</b></div> : null}</div>{aliases.length ? <section><h2>أسماء وتهجئات مرتبطة</h2><div className={styles.tags}>{aliases.map((item) => <span className={styles.tag} key={item.id}>{item.alias}</span>)}</div></section> : null}{children.length ? <section className={styles.section}><h2>مواضع مرتبطة بالتبعية</h2><div className={styles.tags}>{children.map((item) => <span className={styles.tag} key={item.id}>{item.name}</span>)}</div></section> : null}{live ? <p><Link href={`/villages/${encodeURIComponent(live.slug)}`}>فتح صفحة {live.name} في دليل الخدمات والأنشطة الحالي ←</Link></p> : null}<div className={styles.sourceBox}><strong>الإسناد</strong><p>{knowledgeAttribution(place.contributorId)}</p><small>المصدر: {source?.title || 'مصدر موسوعة نقادة'}{source?.year ? ` · ${source.year}` : ''}</small></div></article></div></main>; }