import type {Metadata} from 'next';
import Link from 'next/link';
import {redirect} from 'next/navigation';
import {getContributorAccess} from '@/lib/auth/contributor';
import {resolveSession} from '@/lib/auth/session';
import styles from '../knowledge/knowledge.module.css';
export const metadata:Metadata={title:'لوحة المساهم — دليل نقادة',robots:{index:false,follow:false}};
export const dynamic='force-dynamic';
const permissionLabels:Record<string,string>={'content.create':'إضافة محتوى جديد','content.edit_own':'تعديل المواد التي ساهمت بها','content.propose_correction':'اقتراح تصحيح','media.upload':'رفع وسائط للمراجعة','sources.attach':'إرفاق مصادر','review.view_queue':'عرض قائمة المراجعة','review.mark_needs_verification':'تعليم مادة بأنها تحتاج تحققًا','review.approve_scoped':'اعتماد ضمن نطاق الإشراف','revision.view_history':'عرض سجل الإصدارات','revision.compare':'مقارنة النسخ'};
export default async function ContributorDashboard(){const session=await resolveSession(false);if(!session)redirect('/account/login?next=/contributor');const access=await getContributorAccess(session.accessToken,session.user.id).catch(()=>null);if(!access)return <main id="main-content" className="page-main"><div className={`shell ${styles.wrap} ${styles.detail}`}><article className={styles.detailCard}><span className={styles.eyebrow}>منطقة المساهمين</span><h1>الحساب غير مربوط بصلاحية مساهم</h1><p>هذا الحساب عضو عادي في دليل نقادة حاليًا. صلاحيات المساهم لا تُمنح من بيانات الملف الشخصي، بل من ربط إداري آمن بحساب المساهم.</p><Link href="/account">العودة إلى حسابي ←</Link></article></div></main>;return <main id="main-content" className="page-main"><section className={styles.hero}><div className={`shell ${styles.heroGrid}`}><div><span className={styles.eyebrow}>لوحة المساهم المحمية</span><h1>مرحبًا <em>{access.honorific ? `${access.honorific} ` : ''}{access.displayName}</em></h1><p>{access.roleLabel}{access.primaryWork ? ` · مؤلف «${access.primaryWork}»` : ''}. هذه الصلاحيات منفصلة تمامًا عن صلاحيات مدير الموقع.</p><div className={styles.badges}>{access.badges.map((badge)=><span className={styles.badge} key={badge}>{badge}</span>)}</div></div><aside className={styles.stats}><span><b>{access.permissions.length.toLocaleString('ar-EG')}</b><small>صلاحيات فعالة</small></span><span><b>محمي</b><small>RLS + حساب مسجل</small></span></aside></div></section><div className={`shell ${styles.wrap}`}><section className={styles.section}><div className={styles.sectionHeader}><div><span>صلاحيات الحساب</span><h2>ما يمكنك فعله</h2></div><Link href={`/contributors/${access.slug}`}>الملف العام ←</Link></div><div className={styles.dashboardGrid}>{access.permissions.map((permission)=><div className={styles.permission} key={permission}><i/><strong>{permissionLabels[permission] || permission}</strong></div>)}</div></section><section className={styles.section}><div className={styles.notice}>الحذف النهائي، إدارة المستخدمين، تغيير الصلاحيات، إعدادات الموقع العامة، والكود ليست ضمن صلاحيات المساهم الذهبي.</div></section></div></main>;}